# Generated by Django 5.2.5 on 2025-08-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_bot', '0002_user_phone_number_alter_user_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
